version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - "8080:8080" # Postman
    environment:
      JWT_SECRET: ${JWT_SECRET:-c2Fub3N5c2Fsdm9zLXNlY3JldC1rZXktcGFyYS1qd3QtMjAyNg==}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth-service:8081}
      REPORTE_SERVICE_URL: ${REPORTE_SERVICE_URL:-http://reporte-service:8083}
      GEO_SERVICE_URL: ${GEO_SERVICE_URL:-http://geo-service:8084}
      MATCH_SERVICE_URL: ${MATCH_SERVICE_URL:-http://coincidencias-service:8085}
      NOTIFY_SERVICE_URL: ${NOTIFY_SERVICE_URL:-http://notificaciones-service:8086}
      STORAGE_SERVICE_URL: ${STORAGE_SERVICE_URL:-http://storage-service:8087}

networks:
  default:
    external: true
    name: sanosysalvos-network